# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe4c8be542fd3f10b198b55bf28d891765924732925a5ec6c19cc3c22dec32f2b1b41a71b2b1c196875491db8c5ab8f82bd4b0d51c75ada7a3cf19ec6d2925c

test:
  secret_key_base: cc5917ffdcb09ceefe91d5f0289e2c1801310daf49b3c7a50555929e4de9c6499a43099213b5cb6a494f604f968aacfcdcecff0ce9a8e31dfdf024b17727d2da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
